---
engine: python #
format: pdf
---

# 3 - Desenvolvimento

## Análise Exploratória

Realizaram-se análises estatísticas e gráficos, com ênfase em:

### 1 - A atribuição das pontuações aos estudantes.

\#### Gŕaico de barras comparando notas estudantes de cada escola

### 2 - A distribuição da frequência.

\#### Histograma de frequencia de cada escola

### 3 - Relação entre presença e pontuação.

\#### Heatmap de presença x pontuação por escola

Essas avaliações evidenciaram uma tendência evidente: estudantes que frequentam mais frequentemente tendem a alcançar melhores desempenhos acadêmicos.

## Hiperparâmetros do Random Forest Regressor:

-   Quantidade de estimadores: 100

-   Profundidade máxima (max_depth): Não definida (árvores se desenvolveram de forma autônoma)

-   Estado Aleatório: 42 (para replicabilidade)

## Dicionário de Dummys

::: table
| Variável       | Valor | Significado                                     |
|----------------|:-----:|-------------------------------------------------|
| **schoolsup**  |   1   | Aluno recebe suporte educacional extra          |
| **famsup**     |   1   | Aluno recebe suporte extra da família           |
| **paid**       |   1   | Aluno paga aulas extras                         |
| **activities** |   1   | Aluno participa de atividades extracurriculares |
| **nursery**    |   1   | Aluno frequentou o berçário                     |
| **higher**     |   1   | Aluno pretende fazer curso superior             |
| **internet**   |   1   | Aluno tem acesso à internet em casa             |
| **romantic**   |   1   | Aluno está em um relacionamento romântico       |
:::