project:
  type: book # Tipo de projeto: livro
  output-dir: docs # Pasta onde os arquivos gerados (HTML, PDF) serão salvos

book:
  title: "Projeto Integrador I: Análise de Desempenho Acadêmico x Presença em Sala"
  author: "Seu Nome Completo"
  date: today
  chapters:
    - index.qmd
    - 01-introducao.qmd
    - 02-metodologia.qmd
    - 03-desenvolvimento.qmd
    - 04-resultados.qmd
    - 05-conclusao.qmd
    - referencias.qmd

format:
  pdf:
    pdf-engine: lualatex
    documentclass: article
    include-in-header: contracapa.tex
    toc: false
    number-sections: true
  html:
    toc: true
    number-sections: true
    theme: cosmo
    self-contained: true

execute:
  engine: python
  echo: true
  eval: true
  freeze: false

editor: visual

# --- Configurações de Preview para Host e Porta Padrão ---
preview:
  port: 8808 # Porta padrão para o servidor de pré-visualização (ex: 5000)
  host: 127.0.0.1 # Host padrão (localhost)
  browser: false # Abre o navegador automaticamente (padrão é true)
  # watch-inputs: true # Re-renderiza arquivos quando mudam (padrão é true)
  # navigate: true # Navega automaticamente no navegador quando a saída é atualizada (padrão é true)

# --- Configurações para GitHub Pages e Recursos do Repositório ---
website:
  title: "Projeto Integrador I"
  navbar:
    left:
      - text: "Início"
        href: index.html
  page-navigation: true
  repo-url: https://github.com/ikekenard/projeto-integrador-cdml/grupos-pi-i-2025-projeto_5_ike.git
  repo-actions: [edit, issue]
