project:
  type: book
  output-dir: docs

book:
  title: "Projeto Integrador I: Análise de Desempenho Acadêmico x Presença em Sala"
  author:
    - Ike Gabriel Rodrigues Kenard
    - Leonardo de Lima Amaral
    - Marcelo Saraiva Cavalvanti
    - Vitor Nascimento Franco
    - Rafael Mascarenhas Brown de Andrade
    - Alessandra de Souza Gonçalves
    - Rodrigo Lins Bezerra Magalhaes
  date: today
  chapters:
    - index.qmd
    - 01-introducao.qmd
    - 02-metodologia.qmd
    - 03-desenvolvimento.qmd
    - 04-resultados.qmd
    - 05-conclusao.qmd
    - referencias.qmd

format:
  pdf:
    pdf-engine: lualatex
    documentclass: scrreprt # substitui 'book' e remove 'Chapter X'
    classoption: [openany]
    include-before-body: contracapa.tex
    toc: false
    number-sections: false
    fig-pos: "H"
    fig-align: center
    keep-tex: true
    bibliography: refs.bib
  html:
    toc: true
    number-sections: false
    theme: cosmo
    self-contained: true
    bibliography: refs.bib

execute:
  engine: python
  echo: true
  eval: true
  freeze: false

editor: visual

preview:
  port: 8808
  host: 127.0.0.1
  browser: false

website:
  title: "Projeto Integrador I"
  navbar:
    left:
      - text: "Início"
        href: index.html
  page-navigation: true
  repo-url: https://github.com/ikekenard/projeto-integrador-cdml/grupos-pi-i-2025-projeto_5_ike.git
  repo-actions: [edit, issue]
